
package Proyecto2;

import javax.swing.JOptionPane;

public class Interfaz extends javax.swing.JFrame {
    Funciones f = new Funciones();
    public Interfaz() {
        initComponents(); 
        String Investigacion1= "";
        String Investigacion2= "";
        String Investigacion3= "";
        String Investigacion4= "";
        f.CrearArchivo();
        f.Escribir_txt("");
        f.Escribir_txt("");
        f.Escribir_txt("");
        f.Escribir_txt("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Input1 = new javax.swing.JTextArea();
        AgregarResumen = new javax.swing.JButton();
        BuscarPorClave = new javax.swing.JButton();
        BuscarPorAutor = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Input4 = new javax.swing.JTextField();
        Input5 = new javax.swing.JTextField();
        Input3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Input2 = new javax.swing.JTextArea();
        MostrarResumenes = new javax.swing.JButton();
        BuscarInvestigacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        Titulo.setText("Hash Table Scientific Articles");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        Input1.setColumns(20);
        Input1.setRows(5);
        Input1.setText("Ingrese un nuevo resumen: ");
        jScrollPane1.setViewportView(Input1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 270, 130));

        AgregarResumen.setText("Agregar Resumen");
        AgregarResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarResumenActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        BuscarPorClave.setText("Buscar por Clave");
        BuscarPorClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPorClaveActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarPorClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        BuscarPorAutor.setText("Buscar por Autor");
        getContentPane().add(BuscarPorAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        Salir.setText("Salir");
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        Input4.setText("Ingrese la clave del resumen que desea buscar: ");
        getContentPane().add(Input4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 120, 40));

        Input5.setText("Ingrese el autor principal del resumen que desea buscar: ");
        getContentPane().add(Input5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 120, 40));

        Input3.setText("Ingrese el título del resumen al que desea acceder: ");
        getContentPane().add(Input3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 100, 40));

        Input2.setColumns(20);
        Input2.setRows(5);
        jScrollPane2.setViewportView(Input2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 250, 100));

        MostrarResumenes.setText("Mostrar Resúmenes");
        getContentPane().add(MostrarResumenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        BuscarInvestigacion.setText("Buscar Investigación");
        getContentPane().add(BuscarInvestigacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarPorClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPorClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarPorClaveActionPerformed

    private void AgregarResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarResumenActionPerformed
        try{
          if((Input1.getText().isEmpty()|| Input1.getText().isBlank())){
             JOptionPane.showMessageDialog(null, "El área de texto no puede estar vacía. ");
            }else{
             f.Escribir_txt(Input1.getText());
             JOptionPane.showMessageDialog(null, "Éxito al escribir el archivo");
          }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error, por favor, inténtelo de nuevo");
        }
    }//GEN-LAST:event_AgregarResumenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarResumen;
    private javax.swing.JButton BuscarInvestigacion;
    private javax.swing.JButton BuscarPorAutor;
    private javax.swing.JButton BuscarPorClave;
    private javax.swing.JTextArea Input1;
    private javax.swing.JTextArea Input2;
    private javax.swing.JTextField Input3;
    private javax.swing.JTextField Input4;
    private javax.swing.JTextField Input5;
    private javax.swing.JButton MostrarResumenes;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
